- name: DevOps Lab Local Setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if Splunk exists
      command: docker ps -a -q -f name=splunk-server
      register: splunk_container
      changed_when: false

    - name: Start Splunk if it exists
      command: docker start splunk-server
      when: splunk_container.stdout != ""

    - name: Run Splunk container if not exists
      command: docker run -d --name splunk-server -p 9000:8000 -p 8080:8080 --env-file ./docker/monitor/.env splunk/splunk
      when: splunk_container.stdout == ""

    - name: Run log_generator.py
      command: python3 ./docker/monitor/logs logs.py
