
name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Containers
        run: |
          docker build -t web_image ./docker/web
          docker build -t monitor_image ./docker/monitor

      - name: Run Web Container
        run: |
          docker run -dit -p 8080:80 -v $(pwd)/logs:/var/log/nginx --name web web_image

      - name: Run Splunk Container
        run: |
          docker run -dit -p 8000:8000 \
          -v $(pwd)/logs:/logs \
          -e SPLUNK_START_ARGS=--accept-license \
          -e SPLUNK_PASSWORD=ChintuPadma@45 \
          --name monitor monitor_image

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          pip3 install docker

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml -i ansible/inventory.ini